### ISSUE TITLE
Interlinked Map

### ISSUE THREAD

**Issue by Fatehcis** [jeffreykemp/jk64-plugin-reportmap#1]
Hello,
Thanks for your plugin. Do you have any plans to make it dynamic i.e., similar to PLSQL region on Brookstrut Sample Application. or
https://www.airbnb.com. or
http://offplan-properties.ae/

Where the report interact with the map and vice versa. ?

**Comment by jeffreykemp** [comment]
Hi Fatehcis,

I am indeed planning to augment it in a variety of ways, this was a starting point.

I'd like to at least make the region able to be refreshed via a dynamic action, so that if the source data changes the map can be updated without having to refresh the whole page.

I like the way that the ae site you linked to allows the user to hover over the report, and it automatically shows the info window for the pin on the map. I'll add this to my list of things to do as well.

Thanks very much for your input!

Jeff
