### ISSUE TITLE
Internal server error after ORA APEX patch number:30990551

### ISSUE THREAD

**Issue by marx5** [jeffreykemp/jk64-plugin-reportmap#135]
Greetings,
we have spotted that after installing latest apex patch (number:30990551) the plugin stopped working.

In console is shown "Failed to load resource: the server responded with a status code 500"
And in debug view "Content-Type header is missing" is written after "Rewrite SQL to"
and "Rejecting response header Cache-Control:no-cache" is written after final commit.
We have 6 instances of APEX with version 20.1, and in the 4 instances which have patch applied plugin stopped working, and in remaining two instances the plugin works correctly.
If you have any questions feel free to contact me. 
Best regards,
Martin!

[debug_trace.txt](https://github.com/jeffreykemp/jk64-plugin-reportmap/files/5365242/debug_trace.txt)

**Comment by jeffreykemp** [comment]
No idea at this stage, sorry. I'm not entirely sure that the problem is related to the plugin specifically.

I suggest you hold off on running the patch in the remaining environments until the solution is found.

Some things you could try:
1. Re-install the plugin
2. Re-install the application
3. Upgrade to the latest version of the plugin (if not already on the latest)

If you can reproduce the issue on apex.oracle.com (e.g. by exporting and importing your application) I would be happy to have a look.

Otherwise, your best option will be to contact Oracle support.

**Comment by marx5** [comment]
It looks like it was an easy fix:
In plugin source, ajax function, all I did was remove following line: "sys.htp.p('Cache-Control: no-cache');"
After that map region is rendering successfully!
