### ISSUE TITLE
Error: SyntaxError: Unexpected token , in JSON at position 1618

### ISSUE THREAD

**Issue by JamieKThomas** [jeffreykemp/jk64-plugin-reportmap#136]
Hey, I keep getting this issue when trying to create a pinned map. I've referenced the documentation and my API key and SQL query are both working fine. Any help would be great with this!

**Comment by jeffreykemp** [comment]
I'll need more information in order to diagnose this issue. Can you please, either: (a) create a test case that reproduces the issue on apex.oracle.com; or (b) check the console log / network tab for the response coming from the wwv_flow.ajax call - and post the response data, and post your source query and NLS settings for your session.
![image](https://user-images.githubusercontent.com/15881471/98458003-3701b780-21c7-11eb-9989-fbf36b0d29fe.png)

**Comment by RichardAPickett** [comment]
Hi Jamie, I have come across this too. In my case this occurs when there is no _lat_ or _lng_, ie they are blank in the source data or garbled in some way. It may not be the same for you, but I would suspect the data source in one or more fields/records.

**Comment by jeffreykemp** [comment]
In the next release (v1.5) I'll change it so that if any lat or long is null, the map will not fail but neither will it show the pin (for obvious reasons).

**Comment by RichardAPickett** [comment]
Thank you Jeff
