### ISSUE TITLE
Allow refreshing the data without zooming/panning the map

### ISSUE THREAD

**Issue by xCite1986** [jeffreykemp/jk64-plugin-reportmap#81]
hi jeffrey,

actually i refresh the whole region with ...

`
< script type="text/javascript">
setInterval("jQuery('#my_map').trigger('apexrefresh');", 5000);
< /script>
`
...in the pageheader.

but if i zoom into the map or click a marker they will be resetted with initial zoom level after a few seconds.

is it possible to refresh the lat/lon data only without refreshing the whole region?

thx
alex

**Comment by jeffreykemp** [comment]
Not at the moment, the refresh action always zooms/pans the map so that all the markers are visible, in case some of them have changed since the last time the report was run.

I should be able to add an enhancement to have a javascript API to call to refresh the data without zooming/panning the map.

Thanks

**Comment by jeffreykemp** [comment]
Release 1.1 will include an option "Disable Auto Fit Bounds" which if set will disable this automatic panning and zooming whenever the data is refreshed.

If it is disabled, if you want to re-enable the Auto Fit Bounds feature, it can be done at runtime with:

    $("#map_mymap").reportmap({autoFitBounds:true});

**Comment by jeffreykemp** [comment]
Added in Release 1.1
